// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDulPWQnpAU5pgFmsuTA__woHKLtPgUWaQ',
    appId: '1:897363423490:web:1d414bc2adbf570015d21b',
    messagingSenderId: '897363423490',
    projectId: 'caloriereceipt',
    authDomain: 'caloriereceipt.firebaseapp.com',
    storageBucket: 'caloriereceipt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3U5jZ9owqr_gA_FmjxfD6aYUtS8tIfbM',
    appId: '1:897363423490:android:2b40aba7ae31328115d21b',
    messagingSenderId: '897363423490',
    projectId: 'caloriereceipt',
    storageBucket: 'caloriereceipt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYE-oKA0ZHgWN7YinEn5UjbPKjFZMsKMI',
    appId: '1:897363423490:ios:34b461a3effef68815d21b',
    messagingSenderId: '897363423490',
    projectId: 'caloriereceipt',
    storageBucket: 'caloriereceipt.appspot.com',
    iosClientId: '897363423490-54bhfnuam56lf1e4kabvosv59s8slk9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp.caloriereceipt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYE-oKA0ZHgWN7YinEn5UjbPKjFZMsKMI',
    appId: '1:897363423490:ios:3e2696e8f976ecde15d21b',
    messagingSenderId: '897363423490',
    projectId: 'caloriereceipt',
    storageBucket: 'caloriereceipt.appspot.com',
    iosClientId: '897363423490-3rn0pktrpl9jqcr1o1dce6j1mv0r42og.apps.googleusercontent.com',
    iosBundleId: 'com.example.caloriereceipt.RunnerTests',
  );
}
